from __future__ import annotations

from .domain_types import DriverProfileSpec, PolicyAction, VehicleSpec


VEHICLE_LIBRARY: dict[str, VehicleSpec] = {
    "car": VehicleSpec(
        name="car",
        length=4.4,
        width=1.8,
        desired_speed=9.5,
        acceleration=2.3,
        lateral_flexibility=0.4,
        idle_fuel_liters_per_second=0.00033,
        idle_co2_kg_per_second=0.00076,
    ),
    "bike": VehicleSpec(
        name="bike",
        length=2.0,
        width=0.7,
        desired_speed=8.5,
        acceleration=2.8,
        lateral_flexibility=1.0,
        idle_fuel_liters_per_second=0.00011,
        idle_co2_kg_per_second=0.00025,
    ),
    "auto": VehicleSpec(
        name="auto",
        length=3.2,
        width=1.3,
        desired_speed=7.5,
        acceleration=1.8,
        lateral_flexibility=0.6,
        idle_fuel_liters_per_second=0.00025,
        idle_co2_kg_per_second=0.00058,
    ),
}


DRIVER_PROFILES: dict[str, DriverProfileSpec] = {
    "cautious": DriverProfileSpec(
        name="cautious",
        desired_speed=0.88,
        acceleration=0.85,
        min_gap=1.45,
        encroachment_bias=0.1,
        aggression=0.1,
        restart_gain=0.82,
        reaction_time_mean=2.6,
        reaction_time_jitter=0.55,
        gate_rush_bias=0.08,
        idling_propensity=0.88,
    ),
    "compliant": DriverProfileSpec(
        name="compliant",
        desired_speed=0.95,
        acceleration=0.95,
        min_gap=1.2,
        encroachment_bias=0.2,
        aggression=0.2,
        restart_gain=0.9,
        reaction_time_mean=1.8,
        reaction_time_jitter=0.45,
        gate_rush_bias=0.18,
        idling_propensity=0.92,
    ),
    "opportunistic": DriverProfileSpec(
        name="opportunistic",
        desired_speed=1.0,
        acceleration=1.05,
        min_gap=0.95,
        encroachment_bias=0.55,
        aggression=0.55,
        restart_gain=1.05,
        reaction_time_mean=1.3,
        reaction_time_jitter=0.35,
        gate_rush_bias=0.42,
        idling_propensity=0.95,
    ),
    "assertive": DriverProfileSpec(
        name="assertive",
        desired_speed=1.03,
        acceleration=1.1,
        min_gap=0.85,
        encroachment_bias=0.72,
        aggression=0.72,
        restart_gain=1.12,
        reaction_time_mean=1.0,
        reaction_time_jitter=0.28,
        gate_rush_bias=0.58,
        idling_propensity=0.96,
    ),
    "aggressive": DriverProfileSpec(
        name="aggressive",
        desired_speed=1.08,
        acceleration=1.15,
        min_gap=0.75,
        encroachment_bias=0.9,
        aggression=0.9,
        restart_gain=1.2,
        reaction_time_mean=0.74,
        reaction_time_jitter=0.22,
        gate_rush_bias=0.73,
        idling_propensity=0.98,
    ),
    "reckless": DriverProfileSpec(
        name="reckless",
        desired_speed=1.14,
        acceleration=1.22,
        min_gap=0.62,
        encroachment_bias=1.0,
        aggression=1.0,
        restart_gain=1.28,
        reaction_time_mean=0.52,
        reaction_time_jitter=0.18,
        gate_rush_bias=0.86,
        idling_propensity=0.99,
    ),
}


DEFAULT_ACTIONS: list[PolicyAction] = [
    PolicyAction(name="free_release", mode="free"),
    PolicyAction(
        name="alternating_4s",
        mode="alternating",
        burst_seconds=4.0,
        discipline_bonus=0.15,
    ),
    PolicyAction(
        name="alternating_6s",
        mode="alternating",
        burst_seconds=6.0,
        discipline_bonus=0.2,
    ),
    PolicyAction(
        name="settle_then_alt",
        mode="alternating",
        burst_seconds=4.0,
        settling_delay=2.0,
        discipline_bonus=0.3,
    ),
    PolicyAction(
        name="priority_left",
        mode="priority",
        burst_seconds=4.0,
        priority_side="left",
        priority_window=8.0,
        discipline_bonus=0.18,
    ),
    PolicyAction(
        name="priority_right",
        mode="priority",
        burst_seconds=4.0,
        priority_side="right",
        priority_window=8.0,
        discipline_bonus=0.18,
    ),
]
